name: "Check Pull Request labels"

on:
  pull_request:
    types:
      - labeled
      - unlabeled
    branches:
      - main

permissions: {}

jobs:
  check_labels:
    name: "Check Pull Request labels"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check the labels
        uses: ludeeus/action-require-labels@1.0.0
        with:
          labels: >-
              Breaking Change, Experimental, pr: new-feature,
              pr: enhancement, pr: refactor, pr: bugfix,
              pr: dependency-update